name: Calm DSL Pipeline
defaults:
  run:
    # Needed to load .bashrc for kubectl plugins
    shell: bash -ieo pipefail {0}
on:
  push:
    #branches-ignore:
      #- '**'
    branches:
      # Put your branch name HERE, default is "feat-doc-updat"
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ENVIRONMENT: "kalm-main-20-3"

jobs:
  # Checkout Git repo and copy .local with secrets folder to github workspace
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          ls ${{ github.workspace }}/config
          make help
      - run: echo "ğŸ This job's status is ${{ job.status }}."
